### ISSUE TITLE
wireframe or sketch of design

### ISSUE THREAD

**Issue by rebeccalehew** [juliaguas17/team-project-one#8]

**Comment by juliaguas17** [comment]
https://docs.google.com/presentation/d/1ZLJB5rDlbzpUgWqMFSp8IpcGFb8VSW842pVbD9yJJU4/edit?usp=sharing

**Comment by jengle-dev** [comment]
https://lucid.app/lucidchart/bc65cfcf-d747-4ecc-b8e2-c377db84b286/edit?invitationId=inv_2f570568-a5e9-47d4-a550-5f6d898e1849&referringApp=slack&page=WCvp-83Rj4~-#

**Comment by jengle-dev** [comment]
@juliaguas17  is this officially "done" ?
We can reopen this task if we need to make changes or create a new one.
